#define PPICLF_LRS 6
#define PPICLF_LRP 7
#define PPICLF_LPART 30000
#define PPICLF_LEE 10000
#define PPICLF_LEX 10
#define PPICLF_LEY 10
#define PPICLF_LEZ 10
#define PPICLF_LRP_INT 4

#define PPICLF_JX 1
#define PPICLF_JY 2
#define PPICLF_JZ 3
#define PPICLF_JVX 4
#define PPICLF_JVY 5
#define PPICLF_JVZ 6
#define PPICLF_R_JRHOP 1
#define PPICLF_R_JDP 2
#define PPICLF_R_JPSIP 3
#define PPICLF_R_JUX 4
#define PPICLF_R_JUY 5
#define PPICLF_R_JUZ 6
#define PPICLF_R_JVXZ 7
