#!/bin/bash

function error_quit {
    echo -e "$@"
    echo
    echo -e 'Usage:'
    echo -e './compile_script --clean'
    echo -e '   To clean build direcrtory. Makenek will ask for cleaning 3rd-party libraries.'
    echo
    echo -e './compile_script --all'
    echo -e '   To compile the code.'
    exit 1
}

# Add Framework paths
: "${EMBERSIM_ROOT:?run: source <embersim>/scripts/env.sh first}"
source ${TOOLBOX_SRC}/toolbox_path.sh

# Nek5000 parameters
export CASE="case"
# NEK_SOURCE_ROOT and TOOLBOX_SRC come from scripts/env.sh
export FC="mpif77"${TOOLBOX_INC}
export CC="mpicc"
export PPLIST=""
export USR="frame.o mntrlog_block.o mntrlog.o mntrtmr_block.o mntrtmr.o rprm_block.o rprm.o io_tools_block.o io_tools.o"
USR+=" chkpt.o chkptms.o map2D.o stat.o stat_IO.o math_tools.o"
export SOURCE_ROOT_PPICLF="$(pwd)/ppiclf_build/source"
export FFLAGS=" -I${SOURCE_ROOT_PPICLF} -mcmodel=large"
export USR_LFLAGS=" -L${SOURCE_ROOT_PPICLF} -lppiclF"

# Change a possible relative path to an absolute one; e.g. parRSB doesn't like a relative path
# This is just a hack
cd ${NEK_SOURCE_ROOT}
NEK_SOURCE_ROOT=`pwd`
cd -

# arguments
args=("$@")
argsnr=$#

# check arguments
# parameters number check
if [ $[argsnr] -ne 1 ]; then
    error_quit 'Wrong arguments number!'
fi

for il in "$@"
do
case $il in
        --clean)
                ${NEK_SOURCE_ROOT}/bin/makenek clean
                shift
                ;;
        --all)
                ${NEK_SOURCE_ROOT}/bin/makenek ${CASE}
                shift
                ;;
        *) 
                error_quit 'Wrong argument.'
                ;;
esac
done
